<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-07-11 20:39

$extensionPath = t3lib_extMgm::extPath('readspeaker');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_readspeaker_common' => $extensionClassesPath . 'Common.php',
	'tx_readspeaker_constants_renderer' => $extensionClassesPath . 'Constants/Renderer.php',
	'tx_readspeaker_hooks_pagerendererhook' => $extensionClassesPath . 'Hooks/PageRendererHook.php',
	'tx_readspeaker_services_abstractservice' => $extensionClassesPath . 'Services/AbstractService.php',
	'tx_readspeaker_services_pageservice' => $extensionClassesPath . 'Services/PageService.php',
	'tx_readspeaker_services_renderservice' => $extensionClassesPath . 'Services/RenderService.php',
	'tx_readspeaker_services_typoscriptservice' => $extensionClassesPath . 'Services/TypoScriptService.php',
);
?>